### PR TITLE
changed mqv3 host, version

### PR DESCRIPTION
**Pull request by ulandj**

### CODE REVIEW

**Comment by ulandj** [comment]
@pyeremenko could you please take a look?

**Comment by pyeremenko** [comment]
LGTM

**Comment by rkononov** [comment]
@gerred @treeder who should have merge permissions to this repo?

**Comment by gerred** [comment]
All devs should. Looking.

**Comment by ulandj** [comment]
@gerred any update?

**Comment by gerred** [comment]
Done

**Comment by pyeremenko** [comment]
@gerred, I still haven't write access to merge it :(

**Comment by ulandj** [comment]
@treeder please take a look

**Pull request merged**
